document.writeln("<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; border-width: 0\" bordercolor=\"#111111\" width=\"100%\" id=\"AutoNumber1\" height=\"210\">");
document.writeln("  <tr>");
document.writeln("    <td width=\"23%\" style=\"border-style: none; border-width: medium\" rowspan=\"3\" height=\"108\"><a href=\"http:\/\/www.zkbooks.com\/book.asp?id=5994\" target=\"_blank\"><img src=\"http:\/\/www.zkbooks.com\/bookpic\/20087\/20080703173740.jpg\" style=\"margin:5px;\" border=\"0\" width=\"80\" height=\"100\"><\/a><\/td>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"28\">");
document.writeln("    <p>·<a href=\"http:\/\/www.zkbooks.com\/book.asp?id=5994\" target=\"_blank\" style=\"text-decoration: none\">思想道德修养与法律基础一考通课程代码:3706 <\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"27\">");
document.writeln("    书价:<font color=\"#FF0000\">￥20.00<\/font><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"49\">");
document.writeln("    <a href=\"http:\/\/www.zkbooks.com\/book.asp?id=5994\" target=\"_blank\" style=\"text-decoration: none\"><img src=\"http:\/\/www.zkbooks.com\/Images\/buy.gif\" width=\"85\" height=\"23\" border=\"0\" style=\"margin-top:5px;\"><\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"23%\" style=\"border-style: none; border-width: medium\" rowspan=\"3\" height=\"108\"><a href=\"http:\/\/www.zkbooks.com\/book.asp?id=1598\" target=\"_blank\"><img src=\"http:\/\/www.zkbooks.com\/bookpic\/20090101124136.jpg\" style=\"margin:5px;\" border=\"0\" width=\"80\" height=\"100\"><\/a><\/td>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"45\">");
document.writeln("    <p>·<a href=\"http:\/\/www.zkbooks.com\/book.asp?id=1598\" target=\"_blank\" style=\"text-decoration: none\">毛泽东思想、邓小平理论和[三个代表]重要思想概论[2008版]课程代码:3707<\/a><\/p>");
document.writeln("    <\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"21\">");
document.writeln("    书价:<font color=\"#FF0000\">￥14.00元<\/font><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"77%\" style=\"border-style: none; border-width: medium\" align=\"left\" height=\"38\">");
document.writeln("    <a href=\"http:\/\/www.zkbooks.com\/book.asp?id=1598\" target=\"_blank\"><img src=\"http:\/\/www.zkbooks.com\/Images\/buy.gif\" width=\"85\" height=\"23\" border=\"0\" style=\"margin-top:5px;\"><\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"100%\" colspan=\"2\" style=\"border-style: none; border-width: medium\" height=\"3\">");
document.writeln("    <\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("")